/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConditionResponse { 
    /**
     * Condition UUID
     */
    conditionId: string;
    /**
     * Unit Condition Display Name
     */
    displayName: string;
    /**
     * Unit Condition Code Name
     */
    codeName: string;
}

