/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnitResponse } from './unitResponse';


export interface CreateUnit200Response { 
    data?: Array<UnitResponse>;
    success?: boolean;
    error?: object;
}

