/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DataTypes = 'integer' | 'decimal' | 'string' | 'date' | 'boolean' | 'currency';

export const DataTypes = {
    Integer: 'integer' as DataTypes,
    Decimal: 'decimal' as DataTypes,
    String: 'string' as DataTypes,
    Date: 'date' as DataTypes,
    Boolean: 'boolean' as DataTypes,
    Currency: 'currency' as DataTypes
};

