/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxRateResponse } from './taxRateResponse';


export interface GetTaxRateBySite200Response { 
    data?: Array<TaxRateResponse>;
    success?: boolean;
    error?: object;
}

