/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StandardMapFeatureTypeDto } from './standardMapFeatureTypeDto';
import { Position } from './position';


export interface MapFeatureResponseDto { 
    /**
     * Map Feature ID
     */
    mapFeatureId: string;
    /**
     * Org ID
     */
    orgId: string;
    /**
     * Site ID
     */
    siteId: string;
    /**
     * Location ID
     */
    locationId: string;
    standardMapFeatureType: StandardMapFeatureTypeDto;
    position: Position;
    /**
     * Width of the map feature
     */
    width: number;
    /**
     * Height of the map feature
     */
    height: number;
    /**
     * Depth of the map feature
     */
    depth: number;
    /**
     * Floor of the map feature
     */
    floor?: number;
}

