/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgSettingResponse { 
    /**
     * Organization ID.
     */
    orgId: string;
    /**
     * Number of days before a tenant can move out when requesting.
     */
    daysBeforeMoveOut: number;
    /**
     * Number of minutes between rescheduling a new notification.
     */
    notificationDelayMinutes: number;
    /**
     * Max number for reminders attempt.
     */
    maxReminderAttempts: number;
}

