/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgSiteAmenityResponse { 
    /**
     * Id of the amenity
     */
    amenityId: string;
    /**
     * Amenity name
     */
    amenityName: string;
    /**
     * Amenity description
     */
    amenityDescription: string;
    /**
     * Id of the organzation
     */
    orgId: string;
}

