/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Position { 
    /**
     * The X coordinate of the unit
     */
    x: number;
    /**
     * The Y coordinate of the unit
     */
    y: number;
    /**
     * The Z coordinate of the unit
     */
    z: number;
    /**
     * The rotation of the front foor of the unit
     */
    rotation: number;
}

