/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PricingGroupResponse { 
    /**
     * Pricing Group UUID
     */
    pricingGroupId: string;
    /**
     * The name of the pricing group.
     */
    name: string;
    /**
     * The description of the pricing group.
     */
    description: string;
    /**
     * Unit ID\'s
     */
    unitIds: Array<string>;
}

