/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The value of the setting in string format.
 */
/**
 * @type SettingResponseValue
 * The value of the setting in string format.
 * @export
 */
export type SettingResponseValue = boolean | number | string;

