/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SettingResponseValue } from './settingResponseValue';
import { DataTypes } from './dataTypes';


export interface SettingResponse { 
    /**
     * Setting ID.
     */
    settingId: string | null;
    /**
     * Standard setting type ID.
     */
    standardSettingTypeId: string;
    /**
     * Organization ID.
     */
    orgId: string | null;
    /**
     * Site ID.
     */
    siteId: string | null;
    /**
     * The code name of the setting type.
     */
    codeName: string;
    /**
     * The display name of the setting type.
     */
    displayName: string;
    /**
     * The description of the setting type.
     */
    description: string;
    dataType: DataTypes;
    value: SettingResponseValue;
}
export namespace SettingResponse {
}


