/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StandardMapFeatureTypeDto { 
    /**
     * Standard Map Feature Type ID
     */
    standardMapFeatureTypeId: string;
    /**
     * Code Name
     */
    codeName: string;
    /**
     * Display Name
     */
    displayName: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Resource Name
     */
    resourceName: string;
    /**
     * Hex Color
     */
    hexColor: string;
    /**
     * Opacity
     */
    opacity?: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Depth
     */
    depth: number;
}

