/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UnitFeature { 
    /**
     * Unit Feature UUID
     */
    featureId: string;
    /**
     * Unit Feature Name
     */
    featureName: string;
}

