/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteAmenity } from './siteAmenity';
import { SiteUserRequest } from './siteUserRequest';
import { GenericAddressRequestDto } from './genericAddressRequestDto';
import { SiteType } from './siteType';


export interface UpdateSiteRequest { 
    /**
     * Name
     */
    siteName: string;
    /**
     * Access code length
     */
    accessCodeLength: number;
    /**
     * Site Types
     */
    siteTypes: Array<SiteType>;
    /**
     * Amenity Ids
     */
    siteAmenities?: Array<SiteAmenity>;
    address?: GenericAddressRequestDto;
    /**
     * Site user(s)
     */
    siteUsers?: Array<SiteUserRequest>;
    /**
     * Phone number
     */
    phoneNumber?: string;
    /**
     * Email address
     */
    email?: string;
}

